### ISSUE TITLE
Update tutorial to match the latest version of Storybook. 

### ISSUE THREAD

**Issue by SarthakC** [chromaui/learnstorybook-code#23]

**Comment by tmeasday** [comment]
Hi @SarthakC is there are particular change you are thinking of?

**Comment by Afrowave** [comment]
hey @tmeasday Yes, actually.

I have found that the [Simple Component](https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/) does not show up the styles we import into `.storyboard/config.js`.

If I mistype the index.css to something like `ind.css` I get an error that the module can't be found. Commenting it out or not does not make a difference.

Specs:
```

╭─────────────────────────────────────────────────────╮
│                                                     │
│   Storybook 5.3.0 started                           │
│   7.13 s for manager and 6.84 s for preview         │
│                                                     │
│    Local:            http://localhost:9009/         │
│    On your network:  http://192.168.100.82:9009/    │
│                                                     │
╰────────────────────────────────────────────────────╯
```

**Comment by SarthakC** [comment]
> Hi @SarthakC is there are particular change you are thinking of?

I followed the instructions as per the tutorial. In the **Config** Section of Lesson 2. I could find `config.js` in my `.storybook` folder.

![Screenshot 2020-01-13 at 7 38 51 PM](https://user-images.githubusercontent.com/15229752/72262168-5fb73000-363c-11ea-82b0-df8f472613a0.png)

**Comment by Afrowave** [comment]
The styling for the **taskbox** project in Chromatic also does not show the CSS styling imported in the `.storybook/config.js`.

<img width="808" alt="Screenshot 2020-01-13 at 17 17 31" src="https://user-images.githubusercontent.com/271274/72262785-a00cb300-3628-11ea-9ca4-9412b1c29ead.png">

**Comment by tmeasday** [comment]
HI @SarthakC, ahh, OK, apologies about this. Storybook 5.3 was just released yesterday but we are holding off until the official announcement (probably tomorrow) to make the changes here.
