### ISSUE TITLE
Inaccuracies in tutorial

### ISSUE THREAD

**Issue by davidoudiette** [chromaui/learnstorybook-code#24]
Just started going through the learn Storybook tutorial and it's proving quite frustrating. 

When prompted to modify the config file to:

`// .storybook/main.js
module.exports = {
  stories: ['../src/components/**/*.stories.js'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
};`

It turns out that the path for stories should actually be '../src/components/*.stories.js' (since that's where we've just created stories). 

After getting over this hurdle, now, none of the icons seem to work. It seems like the CSS is relying on a font that's not available (Percolate ?).

**Comment by tmeasday** [comment]
Thanks for the tip about the stories path

Hi @davidoudiette -- perhaps you missed the "Add assets" step from: https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/ ?

**Comment by usrrname** [comment]
I think you might have to ensure your relative path is pointing to `assets/fonts/percolate`

**Comment by jonniebigodes** [comment]
Going to close this issue as the code and the tutorial are in synch. 

Stay safe all
