### ISSUE TITLE
Add assets error

### ISSUE THREAD

**Issue by danielsouzapinna** [chromaui/learnstorybook-code#30]
I'm following this tutorial from learn storybook:
https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/

For some reason when completing lesson 2, my storybook does not display the icons that should be displayed. I do not see any errors in the browser console or in the shell.

Can someone help me? Pls

![Storybook-error-icon](https://user-images.githubusercontent.com/30009784/85058628-c3f49780-b178-11ea-839c-c414104ef08c.png)

**Comment by usrrname** [comment]
I had this problem too before, hopefully these may help you get around it. 

Are you finding any console errors? What are they?

First... did you use the `npx degit` command to install all the assets for fonts and icons that you need? The section about it is under ["Add Assets"](https://www.learnstorybook.com/intro-to-storybook/angular/en/get-started/)

Next, check that the following codeblock you copied from ["Reuse CSS"](https://www.learnstorybook.com/intro-to-storybook/angular/en/get-started/ ) contains relative links that accurately point to your assets/font/folder

```
@font-face {
  font-family: 'percolate';
  src: url('/assets/icon/percolate.eot?-5w3um4');
  src: url('/assets/icon/percolate.eot?#iefix5w3um4') format('embedded-opentype'), url('/assets/icon/percolate.woff?5w3um4')
      format('woff'), url('/assets/icon/percolate.ttf?5w3um4') format('truetype'), url('/assets/icon/percolate.svg?5w3um4')
      format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by dusanbass** [comment]
Hey, I've seen this, but it kinda donsen't work still.

I've changed to "/public/icon/percolate.eot?#iefix5w3um4" but this error occurs:

Module not found: You attempted to import ../public/icon/percolate.eot which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.

There is no "../public.." anywhere in this project.

**Comment by jonniebigodes** [comment]
@danielsouzapinna sorry for the issue you're experiencing with the tutorial. One item i want to ask you. Can you share your package.json, more specifically scripts and dependencies?

@usrrname thank you for jumping, really appreciate it 👍 

Stay safe both of you

**Comment by jonniebigodes** [comment]
Going to close this issue as the code base is now adjusted to fix the underlying issue.

Stay safe everyone
