### ISSUE TITLE
document which Node.js and Yarn versions should be used

### ISSUE THREAD

**Issue by maiermic** [chromaui/learnstorybook-code#45]
I couldn't install dependencies (on branch `angular`) using the latest LTS version of Node.js (`12.19.0`) and yarn `1.22.10`. I got
```
gyp ERR! build error
```
due to V8 header file issues, e.g.
```
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
```
It worked with a previous LTS version of Node.js (`10.15.3`).

Please document which Node.js and Yarn versions work or should be used. I personally prefer `.nvmrc` (see [Node Version Manager](https://github.com/nvm-sh/nvm)) and `.yvmrc` files (see [Yarn Version Manager](https://yvm.js.org/docs/overview)).

**Comment by jonniebigodes** [comment]
Closing this as the codebase was updated to the latest version of Storybook. It was based on the same versions mentioned
