### ISSUE TITLE
Add assets error in React tutorial

### ISSUE THREAD

**Issue by alexoshin** [chromaui/learnstorybook-code#47]
There is an issue in the React tutorial during the [second step](https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/).

After modifying ```.storybook/main.js``` and ```.storybook/preview.js``` in the **Config** section, there is a build error:
```
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/icon/percolate.eot?-5w3um4' in '/home/user/taskbox/src'
```

The error can be resolved by placing the ```public``` directory under the ```src``` directory, rather than in the high-level ```taskbox``` directory, and modifying lines 392-398 of the ```src/index.css``` as following:
```
@font-face {
  font-family: "percolate";
  src: url("./public/icon/percolate.eot?-5w3um4");
  src: url("./public/icon/percolate.eot?#iefix5w3um4") format("embedded-opentype"), url("./public/icon/percolate.woff?5w3um4") format("woff"), url("./public/icon/percolate.ttf?5w3um4") format("truetype"), url("./public/icon/percolate.svg?5w3um4") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Is this the intended directory structure? Otherwise, is there a recommended fix for this issue?

**Comment by Kkim50** [comment]
Can confirm, I ran into the same issue and the above fix worked for me!

**Comment by dusanbass** [comment]
Hey, I don't understand how to apply this fix.
Should the whole public folder be put inside the src?
If so what about the index.html file?

**Comment by jonniebigodes** [comment]
The codebase is updated to factor in the issue that was going on with the styling and React. Closing this.

Stay safe
