### ISSUE TITLE
icon problem

### ISSUE THREAD

**Issue by Ruiz000** [chromaui/learnstorybook-code#67]
I am following the Storybook for React tutorial,and  seem to have hit a problem.

```
ERROR in ./src/index.css (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Module build failed (from ./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js):
Error: Can't resolve './assets/icon/percolate.eot?-5w3um4' in '/Users/mac/react-learn/taskbox/src'
```
what can I do ?

**Comment by jonniebigodes** [comment]
Hi @Ruiz000 thanks for reaching out to us with your issue, we appreciate it. Could you let me know where did it start to happen, at what stage? Also any other context on node/npm versions would help out as well.

Let me know and we'll go from there.

Have a
