### ISSUE TITLE
app.component.spec fails from Angular 'Screens' chapter 

### ISSUE THREAD

**Issue by marckassay** [chromaui/learnstorybook-code#73]
Installing commit 8cb73c6 and executing `npm run test` fails, at least for me. 

I have the following versions installed:

```
E:\learnstorybook-code [(8cb73c6...)]> node -v
v14.19.0
E:\learnstorybook-code [(8cb73c6...)]> npm -v 
6.14.16
```

It would be helpful to elaborate on this note section of  '[Screens](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/screen/)' chapter:

> Don't forget to update the test file src/app/app.component.spec.ts. Or the next time you run your tests they will fail.

Because that's where the test is failing. Perhaps updating dependencies first will be a start.

Hope that helps.

**Comment by jonniebigodes** [comment]
Closing this as it's no longer relevant as the code and tutorial have been updated for Angular 13 and Storybook 6.5.
