### ISSUE TITLE
TypeError: require.context is not a function

### ISSUE THREAD

**Issue by nachoperassi** [chromaui/learnstorybook-code#8]
I'm getting this every time I run the tests

![image](https://user-images.githubusercontent.com/21130898/50379621-2b399600-062d-11e9-8921-92fd929f83e1.png)

**Comment by tmeasday** [comment]
Hi @nachoperassi -- this is a recent problem that has been fixed in the React/English version (https://www.learnstorybook.com/react/en/simple-component/) but perhaps not the version you are reading (or the code examples)..

**Comment by jonniebigodes** [comment]
Going to close this issue as the issue reported here is no longer present. Feel re-open if that's not the case. 

Stay safe all
